# -*- coding: utf-8 -*-
"""TransCox Setting 2 Plotting

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WFwLuFc4k3hNyytHR_5V47tzfmC1YBVN
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
TransCox Setting 2 - High Quality Boxplot Generation
Simplified version for Colab
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.ticker import MultipleLocator

# Set style
plt.style.use('seaborn-v0_8-whitegrid')
sns.set_context("paper", font_scale=1.2)

# Professional color scheme
COLORS = ['#2878B5', '#9AC9DB', '#F8AC8C', '#C82423']

def prepare_boxplot_data(df, metric_name, true_value=None):
    """Prepare data for boxplot"""
    methods = ['Auxiliary', 'Standard Cox', 'Pooled Cox', 'TransCox']
    n_iterations = len(df)

    if metric_name == 'beta1':
        data_cols = ['aux_beta1', 'cox_beta1', 'pooled_beta1', 'transcox_beta1']
        ylabel = 'Beta1 Estimate'
        title = f'Comparison of Beta1 Estimates (Setting 2, n={n_iterations})'
    elif metric_name == 'beta2':
        data_cols = ['aux_beta2', 'cox_beta2', 'pooled_beta2', 'transcox_beta2']
        ylabel = 'Beta2 Estimate'
        title = f'Comparison of Beta2 Estimates (Setting 2, n={n_iterations})'
    elif metric_name == 'mse':
        data_cols = ['aux_mse', 'cox_mse', 'pooled_mse', 'transcox_mse']
        ylabel = 'Mean Squared Error (MSE)'
        title = f'Comparison of Mean Squared Error (Setting 2, n={n_iterations})'
    else:
        raise ValueError("metric_name must be 'beta1', 'beta2', or 'mse'")

    boxplot_stats = {}
    for method, col in zip(methods, data_cols):
        values = df[col].values

        q1 = np.percentile(values, 25)
        median = np.median(values)
        q3 = np.percentile(values, 75)

        iqr = q3 - q1
        lower_bound = q1 - 1.5 * iqr
        upper_bound = q3 + 1.5 * iqr
        outliers = [x for x in values if x < lower_bound or x > upper_bound]

        boxplot_stats[method] = {
            'min': float(np.min(values)),
            'q1': float(q1),
            'median': float(median),
            'q3': float(q3),
            'max': float(np.max(values)),
            'outliers': outliers
        }

    return boxplot_stats, ylabel, title, true_value

def plot_boxplot(data, ylabel, title, true_value=None, figsize=(8, 6), use_log=False):
    """Create high-quality boxplot"""
    methods = list(data.keys())

    box_data = []
    for method in methods:
        stats = data[method]
        box_dict = {
            'label': method,
            'whislo': stats['min'],
            'q1': stats['q1'],
            'med': stats['median'],
            'q3': stats['q3'],
            'whishi': stats['max'],
            'fliers': stats['outliers']
        }
        box_data.append(box_dict)

    fig, ax = plt.subplots(figsize=figsize, dpi=300)

    bplot = ax.bxp(box_data, patch_artist=True, showmeans=False,
                   showfliers=True, vert=True)

    # Customize colors
    for patch, color in zip(bplot['boxes'], COLORS):
        patch.set_facecolor(color)
        patch.set_alpha(0.7)
        patch.set_edgecolor('black')
        patch.set_linewidth(1.0)

    # Customize elements
    for median in bplot['medians']:
        median.set_color('black')
        median.set_linewidth(2.0)

    for whisker in bplot['whiskers']:
        whisker.set_color('black')
        whisker.set_linewidth(1.0)

    for cap in bplot['caps']:
        cap.set_color('black')
        cap.set_linewidth(1.0)

    for flier in bplot['fliers']:
        flier.set_marker('o')
        flier.set_markerfacecolor('red')
        flier.set_markeredgecolor('black')
        flier.set_markersize(5)
        flier.set_alpha(0.5)

    ax.set_ylabel(ylabel, fontsize=14, fontweight='bold')
    ax.set_title(title, fontsize=16, fontweight='bold', pad=15)
    ax.set_xticks(np.arange(1, len(methods) + 1))
    ax.set_xticklabels(methods, rotation=0, fontsize=12)

    if true_value is not None:
        ax.axhline(y=true_value, color='red', linestyle='--', linewidth=2,
                   label=f'True value = {true_value}', alpha=0.7)
        ax.legend(loc='best', fontsize=11, frameon=True, shadow=True)

    if use_log:
        ax.set_yscale('log')
        ax.set_ylabel(ylabel + ' (log scale)', fontsize=14, fontweight='bold')
    else:
        data_min = min([stats['min'] for stats in data.values()])
        data_max = max([stats['max'] for stats in data.values()])
        data_range = data_max - data_min

        y_min = data_min - (data_range * 0.15)
        y_max = data_max + (data_range * 0.15)
        ax.set_ylim(y_min, y_max)

        if data_range < 1:
            ax.yaxis.set_major_locator(MultipleLocator(0.1))
            ax.yaxis.set_minor_locator(MultipleLocator(0.02))
        else:
            ax.yaxis.set_major_locator(MultipleLocator(0.5))
            ax.yaxis.set_minor_locator(MultipleLocator(0.1))

    ax.grid(True, axis='y', linestyle='--', alpha=0.4, linewidth=0.8)
    ax.set_axisbelow(True)

    for spine in ax.spines.values():
        spine.set_linewidth(1.2)
        spine.set_edgecolor('#333333')

    plt.tight_layout()
    return fig

# Main execution
df = pd.read_csv("results_summary.csv")

# Beta1
data_beta1, ylabel1, title1, true1 = prepare_boxplot_data(df, 'beta1', true_value=-0.5)
fig1 = plot_boxplot(data_beta1, ylabel1, title1, true_value=true1, figsize=(8, 6))
fig1.savefig('boxplot_beta1.png', dpi=300, bbox_inches='tight', facecolor='white')
plt.show()

# Beta2
data_beta2, ylabel2, title2, true2 = prepare_boxplot_data(df, 'beta2', true_value=0.5)
fig2 = plot_boxplot(data_beta2, ylabel2, title2, true_value=true2, figsize=(8, 6))
fig2.savefig('boxplot_beta2.png', dpi=300, bbox_inches='tight', facecolor='white')
plt.show()

# MSE
data_mse, ylabel3, title3, _ = prepare_boxplot_data(df, 'mse')
fig3 = plot_boxplot(data_mse, ylabel3, title3, figsize=(8, 6), use_log=True)
fig3.savefig('boxplot_mse.png', dpi=300, bbox_inches='tight', facecolor='white')
plt.show()